### ISSUE TITLE
How would this be used for a mobile app?

### ISSUE THREAD

**Issue by kj7rrv** [KM4YRI/pyFldigi#8]
I saw that this can be used for mobile apps, but I can't find any info on how to do it. Would I need to use a remote server?
73 de KJ7RRV

**Comment by dB-SPL** [comment]
You would still need to run both pyFldigi and Fldigi itself on a computer, although that could be as simple as a Raspberry Pi connected to the radio.

The reference to "Allow a phone or tablet to send and receive FLDIGI messages via a custom app" in the README, doesn't mean you would run the Python module directly on your mobile device.  It's only part of a mobile solution.

Remember, pyFldigi is only a way for Python code to interact with Fldigi; it's not a stand-alone application.  You would still have to write a Python application that accepts input from the user and displays what it receives from Fldigi.

**Comment by kj7rrv** [comment]
Okay. That makes a lot more sense. I had been trying to run Fldigi in Termux to get this to work!
73
